### ISSUE TITLE
Login as another user from group doesn't refresh the set up menu

### ISSUE THREAD

**Issue by cagabi** [emoncms/group#23]

**Comment by cagabi** [comment]
fixed

**Comment by cagabi** [comment]
For Alex, you need to update the groups module, but I wwll still check if anything else needs updated

**Comment by EllaQuigley** [comment]
Carlos,
All our files are up to date and this is still happening.

Ella

**Comment by cagabi** [comment]
It's working for me. Do you mind clearing your cache and try again before I have a proper look?

**Comment by EllaQuigley** [comment]
Ah, ok, this is perhaps the step that we forgot to do, I'm not sure, I'll ask Alex and get back to you.

**Comment by EllaQuigley** [comment]
After the most recent updates, this is now fixed!

**Comment by cagabi** [comment]
Good!
