### ISSUE TITLE
Error: parsererror: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by glynhudson** [emoncms/group#55]
When testing darksidebar PR https://github.com/emoncms/group/pull/54 I get error `Error: parsererror: SyntaxError: Unexpected token < in JSON at position 0`. This is the first time I've installed and tried to use the group module therfore I'm unsure if this error is caused the darksidebar changes or not?

![Screenshot 2019-04-27 at 15 36 31](https://user-images.githubusercontent.com/758844/56851047-6f51e580-6902-11e9-85d2-c99133654b63.png)

**Comment by emrysr** [comment]
fixed in commit of emrysr/emoncms

https://github.com/emrysr/emoncms/commit/6b3cc70a38c5790c526d67730b8d320a01471c88

**Comment by glynhudson** [comment]
I'm still getting the same JSON error after updating this PR. Is that the commit you intended to mention above ^? That commit is related to fixing the bookmark issue on Emoncms core.
